# Generated by Django 3.2.9 on 2021-12-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diffct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_id', models.PositiveIntegerField()),
                ('wbc', models.PositiveIntegerField()),
                ('neut', models.PositiveIntegerField()),
                ('lymp', models.PositiveIntegerField()),
                ('mono', models.PositiveIntegerField()),
                ('baso', models.PositiveIntegerField()),
                ('eos', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('neut_a', models.PositiveIntegerField()),
                ('lymp_a', models.PositiveIntegerField()),
                ('mono_a', models.PositiveIntegerField()),
                ('baso_a', models.PositiveIntegerField()),
                ('eos_a', models.PositiveIntegerField()),
            ],
        ),
    ]
