# Generated by Django 3.2.9 on 2021-12-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diffcount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diffct',
            name='diff_id',
        ),
    ]
